from preprocess import prepare_input
from anomaly import detect_anomaly
from digital_twin import simulate_tool_wear
from predictive import predict_failure
from streaming import get_sensor_data
from api_integration import fetch_cnc_data
from edge import lightweight_predict
from image_utils import process_image
from quantum import quantum_optimize
