from utils.preprocess import prepare_input
from utils.anomaly import detect_anomaly
from utils.digital_twin import simulate_tool_wear
from utils.predictive import predict_failure
from utils.streaming import get_sensor_data
from utils.api_integration import fetch_cnc_data
from utils.edge import lightweight_predict
from utils.image_utils import process_image
from utils.quantum import quantum_optimize
